#
# (C) Copyright 2017 Samsung
# Jaewon Kim <jaewon02.kim@samsung.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_TARGET_S5P6818_DRONE)	+= drone/
obj-$(CONFIG_TARGET_ARTIK710_RAPTOR)	+= artik710_raptor/
