#
# (C) Copyright 2017 Samsung
# Jaewon Kim <jaewon02.kim@samsung.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_TARGET_S5P4418_DRONE)	+= drone/
obj-$(CONFIG_TARGET_ARTIK305_RAPTOR)	+= artik305_raptor/
obj-$(CONFIG_TARGET_ARTIK530_RAPTOR)	+= artik530_raptor/
